apiVersion: v1
kind: Secret
metadata:
  name: git-basic-cred
  annotations:
    tekton.dev/git-1: https://gitlab.ustpace.com # Described below
type: kubernetes.io/basic-auth
stringData:
  username: 
  password: 