apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-vishnu
  containers:
    - name: test-container
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args: ["echo 'Hello' > /usr/share/testfile.txt && sleep 3600"]
      volumeMounts:
        - mountPath: "/usr/share"
          name: test-volume