
apiVersion: v1
kind: Secret
metadata:
  name: ssh-credential
  annotations:
    tekton.dev/git-0: github.com # Described below
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAO5qz3hvxtrMtVq5lPzYg1ALL/iZiht3kG7XchYIepxgAAAKByM2ZKcjNm
    SgAAAAtzc2gtZWQyNTUxOQAAACAO5qz3hvxtrMtVq5lPzYg1ALL/iZiht3kG7XchYIepxg
    AAAECeXB/uCiu+G9l4siRQRvdWyhR3JKb9RRXa15M9UeAT0w7mrPeG/G2sy1WrmU/NiDUA
    sv+JmKG3eQbtdyFgh6nGAAAAHXZpc2hudXByYXNhZC5lZGF0aG9kaUB1c3QuY29t
    -----END OPENSSH PRIVATE KEY-----

  known_hosts: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
